"""add is_active column for soft delete

Revision ID: 605b06ff3812
Revises: f760dcdd84e1
Create Date: 2026-03-12 23:07:26.251120

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '605b06ff3812'
down_revision: Union[str, Sequence[str], None] = 'f760dcdd84e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ambulances', sa.Column('is_active', sa.Boolean(), server_default='1', nullable=False))
    op.add_column('blood_banks', sa.Column('is_active', sa.Boolean(), server_default='1', nullable=False))
    op.add_column('coachings', sa.Column('is_active', sa.Boolean(), server_default='1', nullable=False))
    op.add_column('colleges', sa.Column('is_active', sa.Boolean(), server_default='1', nullable=False))
    op.add_column('doctors', sa.Column('is_active', sa.Boolean(), server_default='1', nullable=False))
    op.add_column('hospitals', sa.Column('is_active', sa.Boolean(), server_default='1', nullable=False))
    op.add_column('mess', sa.Column('is_active', sa.Boolean(), server_default='1', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mess', 'is_active')
    op.drop_column('hospitals', 'is_active')
    op.drop_column('doctors', 'is_active')
    op.drop_column('colleges', 'is_active')
    op.drop_column('coachings', 'is_active')
    op.drop_column('blood_banks', 'is_active')
    op.drop_column('ambulances', 'is_active')
    # ### end Alembic commands ###
