"""Add email verification and password reset fields to User

Revision ID: c8119c923063
Revises: 605b06ff3812
Create Date: 2026-03-23 18:38:43.362822

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c8119c923063'
down_revision: Union[str, Sequence[str], None] = '605b06ff3812'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_verified', sa.Boolean(), nullable=False, server_default=sa.text('true')))
    op.add_column('users', sa.Column('verification_token', sa.String(length=500), nullable=True))
    op.add_column('users', sa.Column('password_reset_token', sa.String(length=500), nullable=True))
    op.add_column('users', sa.Column('token_expiry', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'token_expiry')
    op.drop_column('users', 'password_reset_token')
    op.drop_column('users', 'verification_token')
    op.drop_column('users', 'is_verified')
    # ### end Alembic commands ###
