"""add_lat_long_to_mess_and_others

Revision ID: f760dcdd84e1
Revises: d2d085a324a7
Create Date: 2026-03-12 20:52:18.451628

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f760dcdd84e1'
down_revision: Union[str, Sequence[str], None] = 'd2d085a324a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mess', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('mess', sa.Column('longitude', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mess', 'longitude')
    op.drop_column('mess', 'latitude')
    # ### end Alembic commands ###
